{"uuid": "df95d82b-5bb4-4aba-8711-9934efda7ea1", "children": ["f09d447f-da4c-4378-abd0-b0668674a04f", "8dcac4c3-d32c-45c5-9a78-6fb83c623ddb", "76910760-1a3c-4aa5-8377-4bde3745e66e"], "befores": [{"name": "_xunit_setup_class_fixture_TestAtEating", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\data\\\\record_data.yml'\n", "trace": "  File \"d:\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 854, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 776, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\master\\api_project_2022\\cases\\record\\test_eating.py\", line 38, in setup_class\n    food_id = EatingApi().add_food(\"add_food\").json()[\"id\"]\n  File \"D:\\master\\api_project_2022\\api\\recordapi\\eating.py\", line 17, in __init__\n    with open(_path, encoding=\"utf-8\") as f:\n"}, "start": 1662691401199, "stop": 1662691401199}], "start": 1662691401199, "stop": 1662691401237}