{"name": "食物接口新增米饭", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\data\\\\record_data.yml'", "trace": "self = <class 'cases.record.test_eating.TestAtEating'>\n\n    def setup_class(self):\n>       food_id = EatingApi().add_food(\"add_food\").json()[\"id\"]\n\ncases\\record\\test_eating.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api.recordapi.eating.EatingApi object at 0x000001C12D89D668>\n\n    def __init__(self):\n        self.params[\"token\"] = self.base_token\n    \n        _path = os.path.abspath(\"../../data/record_data.yml\")\n>       with open(_path, encoding=\"utf-8\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\data\\\\record_data.yml'\n\napi\\recordapi\\eating.py:17: FileNotFoundError"}, "start": 1662690963714, "stop": 1662690963714, "uuid": "83bdac05-b863-46b4-be47-8efdecff9947", "historyId": "5e79015efaae6c049f2273f5c4918e3e", "testCaseId": "2b1e45c745ded2b55471d88957d1808f", "fullName": "cases.record.test_eating.TestAtEating#test_add_eating", "labels": [{"name": "feature", "value": "record接口"}, {"name": "story", "value": "食物相关接口"}, {"name": "parentSuite", "value": "cases.record"}, {"name": "suite", "value": "test_eating"}, {"name": "subSuite", "value": "TestAtEating"}, {"name": "host", "value": "DESKTOP-JABQKC0"}, {"name": "thread", "value": "10016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.record.test_eating"}]}