{"uuid": "656c8a1d-df70-4930-a87b-0f3bbf24a761", "children": ["83bdac05-b863-46b4-be47-8efdecff9947", "1c318f80-59a8-4f10-ae14-6d64e1ec9bca", "c739bfd5-f5a1-48a5-9bfe-a148a957bc54"], "befores": [{"name": "_xunit_setup_class_fixture_TestAtEating", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\data\\\\record_data.yml'\n", "trace": "  File \"d:\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 854, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 776, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\master\\api_project_2022\\cases\\record\\test_eating.py\", line 38, in setup_class\n    food_id = EatingApi().add_food(\"add_food\").json()[\"id\"]\n  File \"D:\\master\\api_project_2022\\api\\recordapi\\eating.py\", line 17, in __init__\n    with open(_path, encoding=\"utf-8\") as f:\n"}, "start": 1662690963721, "stop": 1662690963721}], "start": 1662690963721, "stop": 1662690963841}